apiVersion: apps/v1 
kind: Deployment    
metadata:           
  name: angular-k8s-deployment
spec:              
  selector:  
    matchLabels:
      app: angular-k8s-deployment
  replicas: 1  
  template:
    metadata:
      labels:       
        app: angular-k8s-deployment
    spec:
      containers:
        - name: angular-k8s-deployment
          image: petproject1997/pet-project-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
      # restartPolicy: Always      
---
    apiVersion: v1
    kind: Service
    metadata:
      name: angular-k8s-service
      labels:
        name: angular-k8s-deployment
    spec:
      ports:
        - nodePort: 30170 
          port: 4200       
          targetPort: 4200  
          protocol: TCP   
      selector:           
        app: angular-k8s-deployment
      type: NodePort     